### ISSUE TITLE
Adding a Papers-Section?

### ISSUE THREAD

**Issue by LinguList** [glottobank/glottobank.github.io#5]
Adding a paper section may be a good idea, given that more and more research is being publish which has the "funded by glottobank" stamp on it.

**Comment by HedvigS** [comment]
Excellent idea. Btw, for papers in progress, we're keeping issues in Grambank: https://github.com/glottobank/Grambank/issues?q=is%3Aopen+is%3Aissue+label%3Apublication

So if anyone's curious, that's where that is.

**Comment by LinguList** [comment]
Alright, just as we discussed now: we'll keep a papers.md on the glottobank.github.io repo, and people are asked to update this regularly. I'll just get ahead with that.

**Comment by LinguList** [comment]
superseded now by adding this to about/, see here: https://github.com/glottobank/glottobank.github.io/issues/5
